# Generated by Django 2.2.5 on 2021-06-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_db_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_step',
            old_name='Case_id',
            new_name='case_id',
        ),
    ]
